### DISCUSSION TITLE
Problem with Nvidia driver in Mint?

### DISCUSSION THREAD

**Discussion by magarlick2** [linuxmint/discussions#943] [Hardware reviews]
### Releases

Linux Mint 21.x

### Compatibility

Works partially

### Description of the hardware

Dear all. Thanks first and foremost for reading this.

I am running Mint 22.1 Cinnamon but there is no available selection for this OS on this site. Nevertheless, the issue I am going to mention has occurred on every version of Mint (always Cinnamon) I have used since around 20.x. 

My system keeps 'losing contact' with my GPU, which is an Nvidia GTX 4090. I only notice this when I try to run apps that require a GPU, such as Blender or Davinci Resolve. They always run directly after a reboot, so the driver IS being loaded at boot. However, I normally open and close Blender/Davinci multiple times per day.  While most of the time the app 'sees' the GPU and runs normally, I frequently find upon opening Blender that it reports no GPU is found. The only way I know of to then make these apps run properly again is to reboot. This is extremely annoying and has bugged me for over two years.

Can anybody explain why this is happening? But better, does anybody know how to successfully get the apps to recognise the GPU without a reboot? 

My system at this very moment is in such a state. I cannot use Blender or Resolve unless I reboot. Here is the result of inxi -G:

```
Graphics:
  Device-1: NVIDIA AD102 [GeForce RTX 4090] driver: nvidia v: 570.133.07
  Device-2: Logitech Webcam C270 driver: snd-usb-audio,uvcvideo type: USB
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X:
    loaded: nvidia unloaded: fbdev,modesetting,nouveau,vesa
    gpu: nvidia,nvidia-nvswitch resolution: 1: 1024x1280~60Hz
    2: 2560x1440~60Hz 3: 1024x1280~60Hz
  API: EGL v: 1.5 drivers: nvidia,swrast
    platforms: gbm,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 570.133.07
    renderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
```

Seems to me that, if I read that right, the driver isn't loaded at the moment, although it WAS earlier on today and all day yesterday. I have no idea if something I have done has caused this. I doubt it's the actual version of the driver (570). I could try to change it but since this has happened for so long with multiple drivers and OS versions, I don't believe the driver version is relevant.

I am new here. So please let me know if I have overlooked other information you may require.

Thank you.
